# This strict rubocop config should be used before submiting PR and should pass
# Doesn't include:
# - specs

AllCops:
  # Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'config/**/*.rb'
    - 'config/*.rb'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
  RunRailsCops: true
  DisplayCopNames: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Exclude:
    - 'lib/**/version.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/BarePercentLiterals:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals: 
  Enabled: false

Style/Documentation:
  Enabled: false